################################################
#               COSMOLOGY                      #
################################################
Omega_m: 0.31966
Omega_b: 0.05017958681
h: 0.6688
log10As: 3.04070563
ns: 0.9626
f_phi: 1.0

################################################
#               Nuisances                      #
################################################

b1: 1.562362   
b2: 1.732963
b3: 1.913252 
b4: 2.100644         
b5: 2.293210

################################################
#                   Priors                     #
################################################
priors:
  #Cosmological parameters
  Omega_m: [0.275, 0.33]
  #w_c: [0.06, 0.46] # Omega_c*h^2
  Omega_b: [0.04, 0.06] 
  h: [0.61, 0.73]
  1e9As: [1.45, 3.3]
  ns: [0.85, 1.1]
  f_phi: [0.02, 1.0]
  #Nuisance parameters
  b1: [0.8, 3.0]
  b2: [0.8, 3.0]
  b3: [0.8, 3.0]
  b4: [0.8, 3.0]
  b5: [0.8, 3.0] 
  Planck_prior: True
