################################################
#               COSMOLOGY                      #
################################################
Omega_m: 0.31966
Omega_b: 0.04971747
h: 0.6688
log10As: 3.04070563
ns: 0.9626
f_phi: 1.0

################################################
#               Nuisances                      #
################################################

b1_1: 1.562362   
b1_2: 1.732963
b1_3: 1.913252 
b1_4: 2.100644         
b1_5: 2.293210

################################################
#                   Priors                     #
################################################
priors:
  #Cosmological parameters
  w_c: [0.06, 0.46] # Omega_c*h^2
  Omega_b: [0.04, 0.06] # w_b/h^2
  h: [0.61, 0.73]
  1e9As: [1.45, 3.3]
  ns: [0.85, 1.1]
  f_phi: [0.0, 1.0]
  #Nuisance parameters
  b1_1: [0.8, 3.0]
  b1_2: [0.8, 3.0]
  b1_3: [0.8, 3.0]
  b1_4: [0.8, 3.0]
  b1_5: [0.8, 3.0] 
  Planck_prior: True
